### ISSUE TITLE
DDPG is not learning...

### ISSUE THREAD

**Issue by bardas** [abhisheknaik96/MultiAgentTORCS#10]
After some episodes, the car does not learn to drive at all! Is just steering left or right and crushing to the wall. Is it a bug with the code or I have to use specific hyperparameters? I already checked the wiki about the small steps per episode. It is set to 1000. Is anything else I should do?

**Comment by abhisheknaik96** [comment]
Hi @bardas, this is normal behaviour. The state space is quite complicated, and depending on the track chosen, it takes about 200-300 episodes for the agent to learn a decent driving strategy. As suggested in the wiki, turn off the video rendering and check the training status only after a few tens of episodes, it'll take some time.

**Comment by bardas** [comment]
I have waited for 500 episodes and nothing changes... The car just crushes the wall.... What hyperparameters settings work better? Do I miss something?

**Comment by abhisheknaik96** [comment]
I see. What track are you using? Try the chenyi-CG Speedway or chenyi-CG Track 2, they are a little easier.

Also check out the updated version of MADRaS [here](https://github.com/madras-simulator/MADRaS)

**Comment by bardas** [comment]
Are there any chenyi tracks? I have been training it on CG Speedway and on CG Track2. There were no chenyi-CG Speedway or chenyi-CG Track 2. After 1500 episodes, the agent did not learn. I am trying the new version.

**Comment by abhisheknaik96** [comment]
Yes, as mentioned in the [README](https://github.com/abhisheknaik96/MultiAgentTORCS/blob/master/README.MD), the chenyi cars and tracks can be installed from the project in [this link](http://deepdriving.cs.princeton.edu/). Hope this and the new version helps!
