### ISSUE TITLE
Error while running the makefile inside torcs 1.3.6 directory

### ISSUE THREAD

**Issue by Deepak3994** [abhisheknaik96/MultiAgentTORCS#8]
I got the following error while running the "make -j4", after adding "scr-patch"

make: execvp: /bin/bash: Argument list too long
Makefile:30: recipe for target 'restart' failed
make: *** [restart] Error 127

Can anyone help me in resolving this issue.

**Comment by Deepak3994** [comment]
Solved..

**Comment by MehaKaushik** [comment]
For future references: 
https://github.com/madras-simulator/TORCS/pull/1
